// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH5fxKaAkhmjikXdRDWmfrEYzjfkkUWqs',
    appId: '1:216562681903:web:890e2dc886db7b2b719eda',
    messagingSenderId: '216562681903',
    projectId: 'tracker-3e7b3',
    authDomain: 'tracker-3e7b3.firebaseapp.com',
    storageBucket: 'tracker-3e7b3.firebasestorage.app',
    measurementId: 'G-MNW8QC680F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-vloaIcEok6hf85JZnsbPvnlHrmnlmtQ',
    appId: '1:216562681903:android:9dcb7d0c3fbfc0c8719eda',
    messagingSenderId: '216562681903',
    projectId: 'tracker-3e7b3',
    storageBucket: 'tracker-3e7b3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH5fxKaAkhmjikXdRDWmfrEYzjfkkUWqs',
    appId: '1:216562681903:web:85a7505e1ce26dc1719eda',
    messagingSenderId: '216562681903',
    projectId: 'tracker-3e7b3',
    authDomain: 'tracker-3e7b3.firebaseapp.com',
    storageBucket: 'tracker-3e7b3.firebasestorage.app',
    measurementId: 'G-D89NZW08VY',
  );

}